---
title: "Milestone 4"
author: "Carine Hajjar"
date: "2/26/2020"
output: bookdown::pdf_document2
#output: html_document
bibliography: bib.bib
#biblio-style: "apalike"
link_citations: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::write_bib(c("knitr", "stringr"), "bib.bib", width = 60)


library(stargazer)
library(tinytex)
library(rmarkdown)
library(bookdown)
library(gt)
library(car)
library(tidyverse)
library(rstanarm)
library(gtsummary)
library(gtsummary)
library(knitr)
library(stringr)


```

# Notes
I figured out how to do this using a document citing @R-knitr

# GT Table 
```{r gt}

car <- mtcars%>%
  as_tibble(rownames = "car_names")%>%
  select(car_names, mpg, wt, gear)%>%
  rename(Name = car_names, MPG = mpg, Weight = wt, Gears = gear)

gt(car)%>%
  tab_header(
    title = md("**Car Characteristics**"),
    subtitle = md("The mileage, weight, and number of gears in 32 different types of cars")
  )

```

# Regression Table 
```{r stargazer, results="asis", echo=FALSE}

fit <- lm(MPG ~ Weight, data = car)
stargazer(fit, header = FALSE)
```

#Bibliography
          





